import json
import re
from sentence_transformers import SentenceTransformer
from weaviate import Client as WeaviateClient
from tqdm import tqdm
import weaviate

# ---------- CONFIG ---------- #
MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
CHUNK_FILE = "all_combined_chunks1.json"
WEAVIATE_URL = "http://localhost:8080"
CLASS_NAME = "TextileChunk"
BATCH_SIZE = 32

# ---------- STAGE & PARAMETER DICTIONARY ---------- #
PROCESS_NAMES = [
    "ageing",
    "beaming",
    "calendaring",
    "calendering",
    "coating",
    "curing",
    "direct warping",
    "dry",
    "dry print",
    "drying",
    "dye wash",
    "dyeing and washing",
    "finishing",
    "heat set",
    "pigment",
    "print wash",
    "printing",
    "processing",
    "ptg",
    "scouring",
    "scouring and dyeing",
    "scouring and washing",
    "scouring, drying and washing",
    "sectional warping",
    "sizing",
    "testing after coating",
    "testing after printing",
    "testing after processing",
    "testing after weaving",
    "vdr",
    "warp and weft yarn details",
    "washing",
    "weaving",
]

PROCESS_PARAMETERS = {
    "ageing": [
        "ager",
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "design name",
        "dwell time",
        "dwell time(min)",
        "finishing after printing",
        "finishing details after processing",
        "full article",
        "machine used in processing",
        "steam pressure",
        "steam pressure(pound)",
        "steam pressure(psi)",
        "steam pressure in pound",
        "steam pressure in psi",
        "temp",
        "temperature",
        "agening route",
        "route",
    ],
    "beaming": [
        "article no",
        "article number",
        "article_no",
        "beaming reed pitch",
        "beaming speed",
        "chamber 1 high",
        "chamber 1 low",
        "chamber 2 high",
        "chamber 2 low",
        "config_id",
        "cylinder 1",
        "cylinder 2",
        "cylinder 3",
        "cylinder 4",
        "cylinder 5",
        "dry tension fast",
        "dry tension slow",
        "full_article",
        "pressure squeeze roll",
        "pressureimmerssion roll",
        "size -",
        "size concentration",
        "size tension",
        "size tension",
        "sizing m/c speed -",
        "sizing machine speed",
        "sizing speed",
        "sizing wastsge (kg)",
        "spu %",
        "strech",
        "tension t.s.d (1)",
        "tension take up",
        "total ends of warps",
        "water level",
        "beaming route",
        "route",
    ],
    "calendaring": [
        "article no",
        "article number",
        "article_no",
        "bottom 2/ top 2     bowl",
        "bottom 2/top 2 bowl",
        "coating type",
        "design name",
        "finishing after printing",
        "finishing done before coating",
        "full article",
        "full_article",
        "machine used in processing",
        "no of passes",
        "pressure in tons)",
        "pressure  in kg/cm2)",
        "pressure in tons)",
        "pressure in kg",
        "pressure in tons",
        "pressure",
        "speed in meter/min",
        "temp",
        "calenering route",
        "route",
    ],
    "calendering": [
        "article no",
        "article number",
        "article_no",
        "bottom 2/ top 2     bowl",
        "calendaring details",
        "calendring",
        "finishing details after processing",
        "full article",
        "machine used in processing",
        "no of passes",
        "pressure ( tons)",
        "speed mtrs/min",
        "temp",
        "calendering route",
        "route",
        "calenering paarmeters",
    ],
    "coating": [
        "article no",
        "article number",
        "article_no",
        "bomid",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "coating chemicals",
        "coating type",
        "finishing done before coating",
        "full_article",
        "shade",
        "shades",
        "speed  ( +/-2)",
        "type of coating",
        "type of finish",
        "viscosity of pu ( +/-10)",
        "weight ( +/-5)",
        "width after",
        "width after coating",
        "coating route",
        "coating parameters",
        "route",
    ],
    "curing": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "chamber 7 temp ( +/-5)",
        "chamber 8 temp ( +/-5)",
        "clip / pin",
        "coating type",
        "design name",
        "drying / hs / finishing",
        "dwr curring",
        "finishing after printing",
        "finishing details after processing",
        "finishing done before coating",
        "full article",
        "full_article",
        "machine used in processing",
        "p.h. of solution",
        "speed",
        "speed  mtrs/min",
        "stenter curring",
        "stitch end piece with weft straight",
        "wdith after",
        "width after",
        "with / without bianco",
        "with / without overfeed",
        "without/with mangle[ ]",
        "without/with overflow wash",
        "curing route",
        "route",
        "curing parameters",
    ],
    "direct warping": [
        "article no",
        "article number",
        "article_no",
        "beam winding tension",
        "beaming speed",
        "config_id",
        "creel tension (post position)",
        "density",
        "full article",
        "full_article",
        "jumbo winding tension",
        "lease position",
        "number_of_ends_in_warp",
        "oiling",
        "press roll pressure",
        "s.wrap tension contribution",
        "sizing_details",
        "tension washer",
        "total ends of warp",
        "total no of creel ends",
        "traverse",
        "warping m/c speed",
        "warping multiple",
        "warping reed pitch",
        "wastage",
        "yarn breakage",
        "yarn breakage (fluff big)",
        "yarn breakage (fluff small)",
        "yarn breakage (fluff total)",
        "warping speed",
        "warping parameters",
        "warping route",
        "route",
    ],
    "dry": [
        "article no",
        "article number",
        "article_no",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "clip / pin",
        "coating type",
        "drying / hs / finishing",
        "finishing done before coating",
        "full_article",
        "p.h. of solution",
        "speed  mtrs/min",
        "stitch end piece with weft straight",
        "with / without bianco",
        "with / without overfeed",
        "without/with mangle[ ]",
        "without/with overflow wash",
    ],
    "dry print": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "clip / pin",
        "drying / hs / finishing",
        "finishing details after processing",
        "full article",
        "machine used in processing",
        "p.h. of solution",
        "speed  mtrs/min",
        "stenter dry",
        "stitch end piece with weft straight",
        "width after",
        "with / without bianco",
        "with / without overfeed",
        "without/with mangle[ ]",
        "without/with overflow wash",
        "dry print route",
        "dry print parameters",
    ],
    "drying": [
        "after a frame / trolly",
        "article no",
        "article number",
        "article_no",
        "before a frame / trolly",
        "calendaring details",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "chamber 7 temp ( +/-5)",
        "chamber 8 temp ( +/-5)",
        "clip / pin",
        "design name",
        "drying",
        "drying / hs / finishing",
        "dtenter drying",
        "dwr padding",
        "dwr-dry",
        "finishing after printing",
        "finishing details after processing",
        "full article",
        "gsm",
        "machine used in processing",
        "p.h. of solution",
        "speed",
        "speed  mtrs/min",
        "stenter dring",
        "stenter dry",
        "stenter dwr",
        "stenter dwr drying",
        "stenter dying",
        "stitch end piece with weft straight",
        "vdr",
        "vdr-1",
        "wdith after",
        "width after",
        "with / without bianco",
        "with / without overfeed",
        "with / without under feed",
        "with / without underfeed",
        "without/with mangle[ ]",
        "without/with overflow wash",
        "drying",
        "drying route",
        "drying parameters",
        "route",
    ],
    "dye wash parameters": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "cold wash  temp",
        "cold wash end",
        "cold wash ends",
        "cold wash ends-1",
        "cold wash tem-1",
        "cold wash temp",
        "cold wash-1  temp",
        "cold wash-1 ends",
        "cold wash-1 tem",
        "cold wash-2  temp",
        "cold wash-2 ends",
        "dosing ends",
        "dosing temp",
        "dyeing  ends",
        "dyeing  temp",
        "dyeing ends-1",
        "dyeing ends-2",
        "dyeing ends-3",
        "dyeing ends-4",
        "dyeing st ends",
        "dyeing st temp",
        "dyeing st-1 ends",
        "dyeing st-1 temp",
        "dyeing st-2 ends",
        "dyeing st-2 temp",
        "dyeing st-3 ends",
        "dyeing st-3 temp",
        "dyeing st-4 ends",
        "dyeing st-4 temp",
        "dyeing temp-1",
        "dyeing temp-2",
        "dyeing temp-3",
        "dyeing temp-4",
        "finishing details after processing",
        "fixing  ends",
        "fixing  temp",
        "fixing ends",
        "fixing temp",
        "full article",
        "holding time",
        "hot wash ends",
        "hot wash ends 1",
        "hot wash ends 2",
        "hot wash ends-1",
        "hot wash ends-2",
        "hot wash ends-3",
        "hot wash ends-4",
        "hot wash ends-5",
        "hot wash temp",
        "hot wash temp 1",
        "hot wash temp 2",
        "hot wash temp-1",
        "hot wash temp-2",
        "hot wash temp-3",
        "hot wash temp-4",
        "hot wash temp-5",
        "hot wash-1 ends",
        "hot wash-1 temp",
        "hot wash-2 ends",
        "hot wash-2 temp",
        "hot wash-3 ends",
        "hot wash-3 temp",
        "hot wash-4 ends",
        "hot wash-4 temp",
        "jet",
        "machine used in processing",
        "minutes",
        "neutralization ends",
        "neutralization temp",
        "neutralize end",
        "neutralize ends",
        "neutralize temp",
        "neutrialise ends",
        "neutrialise temp",
        "no of ends",
        "p jigger",
        "pressure (kg)",
        "reduction  temp",
        "reduction cleaning ends",
        "reduction cleaning temp",
        "reduction ends",
        "scouring ends",
        "scouring ends-1",
        "scouring temp",
        "scouring temp-1",
        "soaping  temp",
        "soaping ends",
        "soaping temp",
        "dyeing speed",
        "speed (rpm)",
        "temp",
        "tension",
        "time",
        "water",
        "dyeing route",
        "dyeing parameters",
        "route",
    ],
    "dyeing and washing parameters": [
        "article no",
        "article number",
        "article_no",
        "coating type",
        "cold wash",
        "dosing",
        "drain/fill",
        "drain/fill/add",
        "drain/fill/heat",
        "drain/fill/heat/add",
        "dyeing",
        "fill water lt",
        "finishing done before coating",
        "full_article",
        "hot wash",
        "levelling",
        "loading",
    ],
    "finishing parameters": [
        "after a frame / trolly",
        "article no",
        "article number",
        "article_no",
        "before a frame / trolly",
        "calendaring details",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "chamber 7 temp ( +/-5)",
        "chamber 8 temp ( +/-5)",
        "clip / pin",
        "coating type",
        "design name",
        "drying / hs / finishing",
        "finishing after printing",
        "finishing details after processing",
        "finishing done before coating",
        "full article",
        "full_article",
        "machine used in processing",
        "nan",
        "p.h. of solution",
        "speed",
        "speed  mtrs/min",
        "stenter finish",
        "stenterfinishing",
        "stitch end piece with weft straight",
        "wdith after",
        "width after",
        "with / without bianco",
        "with / without overfeed",
        "with / without under feed",
        "without/with mangle[ ]",
        "without/with overflow wash",
        "finishing route",
        "finishing parameters",
        "finishing machine parameters",
    ],
    "heat set parameters": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "chamber 7 temp ( +/-5)",
        "chamber 8 temp ( +/-5)",
        "clip / pin",
        "coating type",
        "drying / hs / finishing",
        "finishing details after processing",
        "finishing done before coating",
        "full article",
        "full_article",
        "heat setting",
        "machine used in processing",
        "p.h. of solution",
        "speed",
        "speed  mtrs/min",
        "stitch end piece with weft straight",
        "width after",
        "with / without bianco",
        "with / without overfeed",
        "with / without under feed",
        "without/with mangle[ ]",
        "without/with overflow wash",
        "heat set route",
        "heat set parameters",
        "heat set machine parameters",
    ],
    "pigment": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "chamber 1 temp ( +/-5)",
        "chamber 2 temp ( +/-5)",
        "chamber 3 temp ( +/-5)",
        "chamber 4 temp ( +/-5)",
        "chamber 5 temp ( +/-5)",
        "chamber 6 temp ( +/-5)",
        "design name",
        "dryer temp. 1",
        "dryer temp. 2",
        "dryer temp. 3",
        "dryer temp. 4",
        "finishing after printing",
        "finishing details after processing",
        "full article",
        "head no. 3",
        "machine used in processing",
        "magnet pressure",
        "screen mesh size",
        "speed",
        "stenter pigment",
        "width after",
        "pigment printing",
        "pigment printing parameters",
        "pigment printing machine parameters",
        "pigment route",
        "pigment parameters",
        "pigment machine parameters",
        "pigment parameter",
        "with / without overfeed",
    ],
    "print wash": [
        "ammonia wash",
        "ammonia wash - no of end",
        "ammonia wash - speed",
        "ammonia wash - temp.",
        "ammonia wash - tension",
        "ammonia wash end",
        "ammonia wash temp",
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "chamber 1 temp",
        "chamber 2 temp",
        "chamber 3 temp",
        "chamber 4 temp",
        "chamber 5 temp",
        "cold wash",
        "cold wash - no of end",
        "cold wash - speed",
        "cold wash - temp.",
        "cold wash - tension",
        "cold wash end",
        "cold wash end-1",
        "cold wash end-2",
        "cold wash ends-2",
        "cold wash temp",
        "cold wash temp-1",
        "cold wash temp-2",
        "design name",
        "drain/fill",
        "drain/fill water",
        "drain/fill water /add",
        "drain/fill water/add",
        "drain/fill water/heat",
        "drain/fill/add",
        "fill water/add",
        "finishing after printing",
        "finishing details after processing",
        "fixing",
        "full article",
        "hot wash",
        "hot wash - no of end",
        "hot wash - speed",
        "hot wash - temp.",
        "hot wash - tension",
        "hot wash ends",
        "hot wash temp",
        "hydro wash - no of end",
        "hydro wash - speed",
        "hydro wash - temp.",
        "hydro wash - tension",
        "loading",
        "loading - speed",
        "loading speed",
        "machine used in processing",
        "neutralization ends",
        "neutralization temp",
        "neutralize",
        "neutralize  - no of end",
        "neutralize  - speed",
        "neutralize  - tension",
        "neutralize - no of end",
        "neutralize - speed",
        "neutralize - temp.",
        "neutralize - tension",
        "no of end",
        "print wash",
        "print wash end",
        "print wash temp",
        "setting",
        "soaping",
        "soaping - no of end",
        "soaping - speed",
        "soaping - temp.",
        "soaping - tension",
        "soaping ends",
        "soaping temp",
        "speed",
        "temp.",
        "tension",
        "wash end",
        "wash temp",
        "water",
        "print wash route",
        "print wash parameters",
        "print wash machine parameters",
        "parameters for print wash",
        "route for print wash",
        "print wash machine parameters",
    ],
    "printing parameters": [
        "1-dryer temp. 1",
        "1-dryer temp. 2",
        "1-dryer temp. 3",
        "1-dryer temp. 4",
        "1-head no. 2",
        "1-head no. 3",
        "1-head no. 4",
        "1-head no. 5",
        "1-head no. 6",
        "1-magnet pressure head no. 2",
        "1-magnet pressure head no. 3",
        "1-magnet pressure head no. 4",
        "1-magnet pressure head no. 5",
        "1-magnet pressure head no. 6",
        "1-rod size head no. 2",
        "1-rod size head no. 3",
        "1-rod size head no. 4",
        "1-rod size head no. 5",
        "1-rod size head no. 6",
        "1-screen mesh size",
        "1-speed",
        "2-dryer temp. 1",
        "2-dryer temp. 2",
        "2-dryer temp. 3",
        "2-dryer temp. 4",
        "2-head no. 2",
        "2-head no. 3",
        "2-head no. 4",
        "2-head no. 5",
        "2-head no. 6",
        "2-magnet pressure head no. 2",
        "2-magnet pressure head no. 3",
        "2-magnet pressure head no. 4",
        "2-magnet pressure head no. 5",
        "2-magnet pressure head no. 6",
        "2-rod size head no. 2",
        "2-rod size head no. 3",
        "2-rod size head no. 4",
        "2-rod size head no. 5",
        "2-rod size head no. 6",
        "2-screen mesh size",
        "2-speed",
        "article no",
        "article number",
        "article_no",
        "design name",
        "dryer temp. 1",
        "dryer temp. 2",
        "dryer temp. 3",
        "dryer temp. 4",
        "finishing after printing",
        "full article",
        "head no. 2",
        "head no. 3",
        "head no. 4",
        "head no. 5",
        "head no. 6",
        "head no. 7",
        "head no. 8",
        "machine used in processing",
        "magnet pressure",
        "magnet pressure head no. 2",
        "magnet pressure head no. 3",
        "magnet pressure head no. 4",
        "magnet pressure head no. 5",
        "magnet pressure head no. 6",
        "magnet pressure head no. 7",
        "magnet pressure head no. 8",
        "rod size",
        "rod size  head no. 4",
        "rod size  head no. 5",
        "rod size  head no. 6",
        "rod size  head no. 7",
        "rod size head no. 2",
        "rod size head no. 3",
        "rod size head no. 4",
        "rod size head no. 5",
        "rod size head no. 6",
        "rod size head no. 7",
        "rod size head no. 8",
        "screen mesh size",
        "printing speed",
        "printing route",
        "printing parameters",
        "printing machine parameters",
        "route for printing",
        "printing machine parameters",
        "print parameters",
        "print machine parameters",
        "print route",
        "print machine route",
    ],
    "processing": [
        "article no",
        "article_no",
        "bomid",
        "calendaring",
        "chemicals used",
        "used chemicals",
        "processing chemicals",
        "chemicals",
        "dyes",
        "col_1",
        "full_article",
        "machine used for processing",
        "required shade",
        "type of finish",
        "width in cm",
    ],
    "ptg": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "finishing details after processing",
        "full article",
        "machine used in processing",
        "printing",
    ],
    "scouring": [
        "article no",
        "article number",
        "article_no",
        "bleaching-1 ends",
        "bleaching-1 temp",
        "bleaching-2 ends",
        "bleaching-2 temp",
        "boil - off  washer",
        "boil - off washer",
        "calendaring details",
        "chamber 1 temp",
        "chamber 2 temp",
        "chamber 3 temp",
        "chamber 4 temp",
        "chamber 5 temp",
        "chamber 6 temp",
        "chamber 7 temp",
        "chamber 8 temp",
        "chemical recp no",
        "coating type",
        "cold wash end",
        "cold wash ends",
        "cold wash temp",
        "desizing ends",
        "desizing temp",
        "desizing/scouring ends",
        "desizing/scouring temp",
        "finishing details after processing",
        "finishing done before coating",
        "full article",
        "full_article",
        "hot wash ends",
        "hot wash ends-1",
        "hot wash ends-2",
        "hot wash temp",
        "hot wash temp-1",
        "hot wash temp-2",
        "hot wash-1 ends",
        "hot wash-1 temp",
        "jet",
        "machine used in processing",
        "manzel washer 1",
        "megalux",
        "megalux bypass",
        "nan",
        "neutralise ends",
        "neutralise temp",
        "neutralization ends",
        "neutralization temp",
        "no of ends",
        "scouring ends",
        "scouring ends-1",
        "scouring ends-2",
        "scouring temp",
        "scouring temp-1",
        "scouring temp-2",
        "scouring-1 ends",
        "scouring-1 temp",
        "scouring-2 ends",
        "scouring-2 temp",
        "speed in scouring",
        "temp",
        "tension",
        "water",
        "scouring route",
        "scouring parameters",
        "scouring machine parameters",
        "scouring parameter",
        "scouring machine parameter",
        "scouring machine route",
        "route",
    ],
    "scouring and dyeing": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "cold wash ends-1",
        "cold wash tem-1",
        "dyeing st-1 ends",
        "dyeing st-1 temp",
        "dyeing st-2 ends",
        "dyeing st-2 temp",
        "dyeing st-3 ends",
        "dyeing st-3 temp",
        "finishing details after processing",
        "full article",
        "hot wash ends-1",
        "hot wash ends-2",
        "hot wash temp-1",
        "hot wash temp-2",
        "machine used in processing",
        "neutralization ends",
        "neutralization temp",
        "no of ends",
        "scouring ends",
        "scouring temp",
        "speed",
        "temp",
        "tension",
        "water",
        "dyeing and scouring route",
        "dyeing parameters",
    ],
    "scouring and washing": [
        "article no",
        "article number",
        "article_no",
        "bleach end",
        "bleach temp",
        "bleaching end-1",
        "bleaching end-2",
        "bleaching ends",
        "bleaching ends-1",
        "bleaching ends-2",
        "bleaching temp",
        "bleaching temp-1",
        "bleaching temp-2",
        "bleaching-1 ends",
        "bleaching-1 temp",
        "bleaching-2 ends",
        "bleaching-2 temp",
        "calendaring details",
        "chamber 1 temp",
        "chamber 1 temp-1",
        "chamber 2 temp",
        "chamber 2 temp-1",
        "chamber 3 temp",
        "chamber 3 temp-1",
        "chamber 4 temp",
        "chamber 4 temp-1",
        "chamber 5 temp",
        "chamber 5 temp-1",
        "chamber 6 temp",
        "chamber 7 temp",
        "chamber 8 temp",
        "chemical recp no",
        "chemical recp no-1",
        "cold wash end",
        "cold wash end-1",
        "cold wash end-3",
        "cold wash ends",
        "cold wash ends-1",
        "cold wash ends-2",
        "cold wash ends-3",
        "cold wash tem-1",
        "cold wash temp",
        "cold wash temp-1",
        "cold wash temp-2",
        "cold wash temp-3",
        "cold wash-1 ends",
        "cold wash-1 temp",
        "cold wash-2 ends",
        "cold wash-2 temp",
        "desizing ends",
        "desizing temp",
        "finishing details after processing",
        "frn wash ends",
        "frn wash temp",
        "full article",
        "hot  wash ends",
        "hot wash ends",
        "hot wash ends-1",
        "hot wash ends-2",
        "hot wash temp",
        "hot wash temp-1",
        "hot wash temp-2",
        "hot wash-1 ends",
        "hot wash-1 temp",
        "hot wash-2 ends",
        "hot wash-2 temp",
        "jet",
        "machine used in processing",
        "manzel washer 2",
        "megalux",
        "megalux bypass",
        "minutes",
        "nan",
        "neutralise end",
        "neutralise ends",
        "neutralise temp",
        "neutralization ends",
        "neutralization ends-2",
        "neutralization temp",
        "neutralization temp-2",
        "neutrelise ends",
        "neutrelise temp",
        "neutrelization ends",
        "neutrelization temp",
        "no of ends",
        "oxalic wash ends",
        "oxalic wash temp",
        "peroxide process end",
        "peroxide process temp",
        "pressure (kg)",
        "scouring ends",
        "scouring ends-1",
        "scouring ends-2",
        "scouring temp",
        "scouring temp-1",
        "scouring temp-2",
        "scouring-1 ends",
        "scouring-1 temp",
        "scouring-2 ends",
        "scouring-2 temp",
        "scouring-3 ends",
        "scouring-3 temp",
        "scouring/desizing ends",
        "scouring/desizing temp",
        "seting",
        "setting",
        "settting",
        "soaping ends",
        "soaping temp",
        "washing machine speed",
        "machine speed in washing",
        "speed (rpm)",
        "temp",
        "tension",
        "water",
        "scouring and washing route",
        "scouring and washing parameters",
    ],
    "scouring, drying and washing": [
        "article no",
        "article number",
        "article_no",
        "bleaching end-1",
        "bleaching end-2",
        "bleaching ends",
        "bleaching ends 1",
        "bleaching ends 2",
        "bleaching ends-1",
        "bleaching ends-2",
        "bleaching temp",
        "bleaching temp 1",
        "bleaching temp 2",
        "bleaching temp-1",
        "bleaching temp-2",
        "bleaching-1 ends",
        "bleaching-1 temp",
        "bleaching-2 ends",
        "bleaching-2 temp",
        "calendaring details",
        "cold wash  ends",
        "cold wash  ends-2",
        "cold wash end-1",
        "cold wash end-3",
        "cold wash end-4",
        "cold wash end-5",
        "cold wash ends",
        "cold wash ends-1",
        "cold wash ends-2",
        "cold wash ends-3",
        "cold wash tem-1",
        "cold wash temp",
        "cold wash temp-1",
        "cold wash temp-2",
        "cold wash temp-3",
        "cold wash temp-4",
        "cold wash temp-5",
        "cold wash-1 end",
        "cold wash-1 ends",
        "cold wash-1 temp",
        "cold wash-2 end",
        "cold wash-2 ends",
        "cold wash-2 temp",
        "desizing ends",
        "desizing temp",
        "dyeing st-1 ends",
        "dyeing st-1 temp",
        "dyeing st-2 ends",
        "dyeing st-2 temp",
        "dyeing st-3 ends",
        "dyeing st-3 temp",
        "dyeing st-4 ends",
        "dyeing st-4 temp",
        "finishing details after processing",
        "fixing end",
        "fixing ends",
        "fixing ends-2",
        "fixing temp",
        "fixing temp-2",
        "fixing temps",
        "frn wash ends",
        "frn wash temp",
        "full article",
        "hot wash  ends-1",
        "hot wash  ends-2",
        "hot wash ends",
        "hot wash ends-1",
        "hot wash ends-2",
        "hot wash ends-3",
        "hot wash ends-4",
        "hot wash ends-5",
        "hot wash ends-6",
        "hot wash temp",
        "hot wash temp-1",
        "hot wash temp-2",
        "hot wash temp-3",
        "hot wash temp-4",
        "hot wash temp-5",
        "hot wash temp-6",
        "hot wash-1 ends",
        "hot wash-1 temp",
        "hot wash-2  ends",
        "hot wash-2 ends",
        "hot wash-2 temp",
        "hot wash-3 ends",
        "hot wash-3 temp",
        "hot wash-4 ends",
        "hot wash-4 temp",
        "hot wash-5 ends",
        "hot wash-5 temp",
        "jet",
        "machine used in processing",
        "neutralization ends",
        "neutralization ends-1",
        "neutralization ends-2",
        "neutralization temp",
        "neutralization temp-1",
        "neutralization temp-2",
        "neutralize ends",
        "neutralize temp",
        "neutrealise ends",
        "neutrealise temp",
        "neutrelise ends",
        "neutrelise temp",
        "no of ends",
        "reduction cleaning ends",
        "reduction cleaning temp",
        "reduction clear end",
        "reduction clear temp",
        "scouring end",
        "scouring ends",
        "scouring ends-1",
        "scouring ends-2",
        "scouring temp",
        "scouring temp-1",
        "scouring temp-2",
        "scouring-1 ends",
        "scouring-1 temp",
        "scouring-2 ends",
        "scouring-2 temp",
        "soaping ends",
        "soaping temp",
        "soping ends",
        "soping temp",
        "speed",
        "temp",
        "tension",
        "water",
    ],
    "sectional warping": [
        "article no",
        "article number",
        "article_no",
        "beam winding tension",
        "beaming reed pitch",
        "beaming speed",
        "compaction factor",
        "config_id",
        "creel tension (post position)",
        "density",
        "ends / section -",
        "fabric",
        "full article",
        "full_article",
        "lease position",
        "number_of_ends_in_warp",
        "oiling",
        "press roll pressure",
        "s.wrap tension contribution",
        "section width in cms",
        "sizing m/c speed -",
        "sizing_details",
        "tension t.s.d (1)",
        "tension take up",
        "total ends of warp",
        "traverse",
        "warping m/c speed",
        "wastage",
        "sectional warping route",
        "sectional warping parameters",
        "sectional warping machine parameters",
        "sectional warping parameter",
        "sectional warping machine parameter",
        "sectional warping machine route",
        "warping route",
    ],
    "sizing": [
        "article no",
        "article number",
        "article_no",
        "beaming reed pitch",
        "beaming speed",
        "chamber 1 high",
        "chamber 1 low",
        "chamber 2 high",
        "chamber 2 low",
        "config_id",
        "cylinder 1",
        "cylinder 2",
        "cylinder 3",
        "cylinder 4",
        "cylinder 5",
        "dry tension fast",
        "dry tension slow",
        "full_article",
        "pressure squeeze roll",
        "pressureimmerssion roll",
        "size -",
        "size concentration",
        "size tension fast",
        "size tension slow",
        "sizing m/c speed -",
        "sizing wastsge (kg)",
        "spu %",
        "strech",
        "tension t.s.d (1)",
        "tension take up",
        "total ends in warp",
        "water -",
        "sizing route",
        "sizing parameters",
        "sizing machine parameters",
        "sizing parameter",
        "sizing machine parameter",
        "sizing machine route",
        "sizing process route",
    ],
    "testing after coating": [
        "%bias",
        "fabric bias distortion percentage",
        "fabric bow distortion percentage",
        "%bow",
        "%bow-inch",
        "%skew",
        "%skew-inch",
        "abra emery cycle",
        "abso.of water drop-after washsec",
        "abso.of water drop-before sec",
        "absorption of water drop- sec",
        "add on %",
        "add on(gms)",
        "adhesion to backing (n/cm) 8310se",
        "apcycl@1/2 inch (cfm)",
        "apcycl@1/2 inch (l/m2/s)",
        "appearance after 5x hl",
        "bend lngth-wp mn.cm2",
        "blocking test",
        "breathtest-mg/cm2/h",
        "cf to light",
        "chunk_part",
        "co-eff.frict-wt",
        "co-eff.frict.wp",
        "testing specifications",
        "abrasion resistance after coating",
        "coated abrasion resistance using p600emery at 9kpa after 150 cycles",
        "coated abrasion resistance using p600emery at 9kpa after 30 cycles",
        "coated abrasion resistance using p600emery at 9kpa after 50 cycles",
        "coated abrasion resistance using unspecified abradant at 9kpa after 10000 cycles",
        "coated abrasion resistance using unspecified abradant at unspecified pressure after unspecified number of cycles",
        "coated abrasion resistance using wool at 12kpa after 100000 cycles",
        "coated abrasion resistance using wool at 12kpa after 75000 cycles",
        "coated abrasion resistance using wool at 9kpa after 15000 cycles",
        "coated abrasion resistance using wool at 9kpa after 50000 cycles",
        "coated abrasion resistance using wool at 9kpa after 60000 cycles",
        "coated abrasion resistance using wool at 9kpa after 90000 cycles",
        "coated abrasion resistance using wool at unspecified pressure after 1 cycles",
        "coated air permeability at 1/2 inch pressure in ft3/ft2/m",
        "coated air permeability at 1/2 inch pressure in l/m2/s",
        "coated air permeability at 10 inch pressure in cm3/cm2/s",
        "coated air permeability at 10 inch pressure in ft3/ft2/m",
        "coated air permeability at 100 pas pressure in cm3/cm2/s",
        "coated air permeability at 100 pas pressure in l/m2/s",
        "coated air permeability at 100 pas pressure in mm/s",
        "coated air permeability at 10mm pressure in cm3/cm2/s",
        "coated air permeability at 200 pas pressure in mm/s",
        "coated air permeability at 25mm pressure in cc/sec/cm2",
        "coated air permeability at 500 pas pressure in l/m2/s",
        "air permeability after coating",
        "ap after coating",
        "coated breaking strength of warp in dan",
        "coated breaking strength of warp in kgf",
        "coated breaking strength of warp in lbf",
        "coated breaking strength of warp in n",
        "coated breaking strength of weft in dan",
        "coated breaking strength of weft in kgf",
        "coated breaking strength of weft in lbf",
        "coated breaking strength of weft in n",
        "coated bursting strength in kgf/cm²",
        "breaking strength after coating",
        "bs after coating",
        "coated colourfastness to perspiration (acid) change in shade",
        "coated colourfastness to perspiration (acid) staining on acr",
        "coated colourfastness to perspiration (acid) staining on act",
        "coated colourfastness to perspiration (acid) staining on cot",
        "coated colourfastness to perspiration (acid) staining on nyl",
        "coated colourfastness to perspiration (acid) staining on pol",
        "coated colourfastness to perspiration (acid) staining on wol",
        "coated colourfastness to perspiration (alkaline) change in shade",
        "coated colourfastness to perspiration (alkaline) staining on acr",
        "coated colourfastness to perspiration (alkaline) staining on act",
        "coated colourfastness to perspiration (alkaline) staining on cot",
        "coated colourfastness to perspiration (alkaline) staining on nyl",
        "coated colourfastness to perspiration (alkaline) staining on pol",
        "coated colourfastness to perspiration (alkaline) staining on wol",
        "colour fastness to perspiration after coating",
        "colour fastness to perspiration",
        "coated colourfastness to rubbing (dry)",
        "coated colourfastness to rubbing (dry)  wp",
        "coated colourfastness to rubbing (dry)  wt",
        "coated colourfastness to rubbing (wet)",
        "coated colourfastness to rubbing (wet)  wp",
        "coated colourfastness to rubbing (wet)  wt",
        "colour fastness to rubbing",
        "coated colourfastness to sea water change in shade",
        "coated colourfastness to sea water staining on acr",
        "coated colourfastness to sea water staining on act",
        "coated colourfastness to sea water staining on cot",
        "coated colourfastness to sea water staining on nyl",
        "coated colourfastness to sea water staining on pol",
        "coated colourfastness to sea water staining on wol",
        "colour fastness to sea water",
        "color fastness to sea water",
        "colour fastness to sea water after coating",
        "coated colourfastness to washing change in shade",
        "coated colourfastness to washing staining on acr",
        "coated colourfastness to washing staining on act",
        "coated colourfastness to washing staining on cot",
        "coated colourfastness to washing staining on nyl",
        "coated colourfastness to washing staining on pol",
        "coated colourfastness to washing staining on wol",
        "colur fastness to wash",
        "colour fastness to washing",
        "colour fastness to wash after coating",
        "colour fastness to washing after coating",
        "cf to wash after coating",
        "cf to washing after coating",
        "coated colourfastness to water change in shade",
        "coated colourfastness to water staining on acr",
        "coated colourfastness to water staining on act",
        "coated colourfastness to water staining on cot",
        "coated colourfastness to water staining on nyl",
        "coated colourfastness to water staining on pol",
        "coated colourfastness to water staining on wol",
        "colour fastness to water",
        "colour fastness to water on different fibres"
        "coated delta e (δe) under primary light (f11 10°)",
        "coated delta e (δe) under secondary light (d65 10°)",
        "coated delta e (δe) value",
        "coated dimensional stability of warp after 2 washes",
        "coated dimensional stability of warp after 3 washes",
        "coated dimensional stability of warp after 5 washes",
        "coated dimensional stability of warp after one washes",
        "coated dimensional stability of warp in cold water",
        "coated dimensional stability of warp in hot water",
        "coated dimensional stability of warp to heat",
        "coated dimensional stability of weft after 2 washes",
        "coated dimensional stability of weft after 3 washes",
        "coated dimensional stability of weft after 5 washes",
        "coated dimensional stability of weft after one washes",
        "coated dimensional stability of weft in cold water",
        "coated dimensional stability of weft in hot water",
        "coated dimensional stability of weft to heat",
        "ds of warp",
        "dimensional stablity of warp",
        "ds of weft",
        "dimensional stability of weft",
        "ds of warp after coating",
        "coated ends per 10cms",
        "coated ends per cms",
        "coated ends per dm",
        "coated fabric elongation in warp direction (fabric growth after 30mm-wp)",
        "coated fabric elongation in warp direction (wp)",
        "coated fabric elongation in weft direction (fabric growth after 30mm-wt)",
        "coated fabric elongation in weft direction (of fabric stretch-wt(15n))",
        "coated fabric elongation in weft direction (wt)",
        "coated picks per 10cms",
        "coated picks per cms",
        "coated picks per dm",
        "coated picks per inch",
        "coated tear strength of warp in dan",
        "coated tear strength of warp in kgf",
        "coated tear strength of warp in lbf",
        "coated tear strength of warp in n",
        "coated tear strength of warp using elmendorf method in dan",
        "coated tear strength of warp using elmendorf method in kgf",
        "coated tear strength of warp using elmendorf method in lbf",
        "coated tear strength of weft in dan",
        "coated tear strength of weft in kgf",
        "coated tear strength of weft in lbf",
        "coated tear strength of weft in n",
        "coated tear strength of weft using elmendorf method in dan",
        "coated tear strength of weft using elmendorf method in kgf",
        "coated tear strength of weft using elmendorf method in lbf",
        "coated thickness in inch",
        "coated thickness in micron",
        "coated thickness in mil",
        "coated thickness in mm",
        "coated water proofness of weld zone tested at 100°c for 1 hour(s)",
        "coated water proofness tested at 100°c",
        "coated water proofness tested at 100°c for 1 hour(s)",
        "coated water proofness tested at 100°c for 60 minutes",
        "coated water proofness tested at 110°c for 90 seconds",
        "coated water proofness tested at 140°c for 60 seconds",
        "coated water proofness tested at 20°c",
        "coated water proofness tested at 30°c for 30 minutes",
        "coated water proofness tested at 30°c for 60 minutes",
        "coated water proofness tested at 60°c for 30 minutes",
        "coated water proofness tested at 60°c for 60 minutes",
        "coated water proofness tested at 80°c for 60 seconds",
        "coated water proofness tested at 80°c with minimum pressure of 80 cm",
        "coated water proofness using dynamic method",
        "coated water proofness with minimum pressure of 0.4 bar",
        "coating_formulation",
        "crimp test % -wp",
        "crimp test % -wt",
        "deter.of shrink.after1wash @40°c-wp",
        "deter.of shrink.after1wash @40°c-wt",
        "deter.of shrink.after5wash @40°c-wp",
        "deter.of shrink.after5wash @40°c-wt",
        "finish_and_calendaring_details",
        "flex res.-crack",
        "flex res.-flaking",
        "flex res.-wrinkle",
        "fr test (a. flame)",
        "fr test (a. glow)",
        "is_split_chunk",
        "majoraxis-drop spread-afterwashcm",
        "majoraxis-drop spread-beforewashcm",
        "melting point",
        "metamerism f11/d65 mi",
        "nature of coating",
        "nature of dyes",
        "nature of fiber",
        "oil content%",
        "original_stage_name",
        "peel st.-wp gmf",
        "peel st.-wp n",
        "peel st.-wt n",
        "peelrest.after50wash",
        "per.of set %shrink.-wp",
        "per.of set %shrink.-wt",
        "per.of set ap@1/2 inch (ft3/ft2/m)",
        "per.of set thick inch",
        "ph value",
        "ph value-other color",
        "ph value-white to pastel color",
        "pilling (7000 tours)",
        "pilling after (18000 revs.)",
        "pilling resis.martindale(5000 rubs)",
        "relaxation shrinkage- wp",
        "relaxation shrinkage- wt",
        "res. to acc.ageing",
        "res. to low temp.",
        "res. to low temp.(-40°c for 6 hrs.)",
        "res.to acce. ageing(70±1°c/168hrs.)",
        "seal st.-wp n",
        "seal st.-wt n",
        "seam slippage (cm)-wp",
        "seam slippage (cm)-wt",
        "seam slippage of yarn(mm)-wp",
        "seam slippage of yarn(mm)-wt",
        "sp pu film- wp",
        "sp pu film- wt",
        "sp pu film-wp",
        "sp pu film-wt",
        "spreading speed bottom-after 3 wash",
        "ss-wp kgf",
        "ss-wt kgf",
        "type of weave",
        "warp_fibre",
        "water proofness initial (pa)",
        "water repellency",
        "water repellency- after 2 wash",
        "water repellency- after 5 wash",
        "water repellency- before wash",
        "water repellency-after5wash+line",
        "water repellency-after5wash+tumble",
        "water repellency-initial",
        "water resis.(6 kpa/min.)after 5wash",
        "water resistance-after 5 wash-250mm",
        "water resistance-after5wash-10000mm",
        "water resistance-before wash-250mm",
        "water resistance-beforewash-10000mm",
        "water soluble %",
        "water vapor res.re (m2/pa/w)",
        "watervaporresit.",
        "weft_fibre",
        "weight gsm",
        "weight gsm- coated",
        "weight oz/yd2",
        "whiteness ind-cie",
        "wick.height 5xhl after 10min.-wp",
        "wick.height 5xhl after 10min.-wt",
        "wick.height 5xhl after 30min.-wp",
        "wick.height 5xhl after 30min.-wt",
        "wick.height-original after10min.-wp",
        "wick.height-original after10min.-wt",
        "wick.height-original after30min.-wp",
        "wick.height-original after30min.-wt",
        "width cm",
        "width cm (c to c)",
        "width cm (l to l)",
        "width cm (p to p)",
        "width cm (s to s)",
        "width inch",
        "width mm",
        "width",
        "fabric bias distortion percentage",
        "fabric bow distortion percentage",
        "fabric bow distortion per inch",
        "fabric skew distortion percentage",
        "fabric skew distortion per inch",
        "fabric thickness",
        "test specifications" "testing specifications",
        "testing specifications after coating",
        "testing standards for coating",
        "test standards for coating",
        "test standards",
        "testing details",
        "testing details after coating",
        "testing after coating",
        "test specification",
        "test specification",
        "fabric thickness",
        "breaking strength",
        "bs",
        "tear strength",
        "perspiration",
        "fastness",
        "cf" "colourfastness",
        "color fastness",
        "colorfastness",
        "dimensional stability",
        "ds",
        "fabric elongation after coating",
        "fabric elongation",
        "water staining",
        "staining tets standards",
        "staining",
        "difference under primary light f11",
        "drop absorption",
        "drop spread",
        "water proofness",
        "water repellency",
        "water resistance",
        "wicking height",
        "coating adhesion",
        "peel strength",
        "peel resistance",
        "seal strength",
        "seam slippage",
        "pilling",
        "vapor resistance",
        "oil content percentage",
        "sp pu film",
        "fabric durability",
        "fabric strength",
        "rub resistance",
        "abrasion test",
        "abrasion",
        "water absorption",
    ],
    "testing after printing": [
        "%bias",
        "%bow",
        "%skew",
        "abra emery cycle",
        "abso.of water drop-after washsec",
        "abso.of water drop-before sec",
        "absorption of water drop- sec",
        "add on(gms)",
        "blocking test",
        "breathtest-mg/cm2/h",
        "cf to light",
        "chunk_part",
        "deter.of shrink.after1wash @40°c-wp",
        "deter.of shrink.after1wash @40°c-wt",
        "finish",
        "flex res.-crack",
        "flex res.-flaking",
        "flex res.-wrinkle",
        "fr test (a. flame)",
        "fr test (a. glow)",
        "fr test (char length",
        "gloss value (gu)",
        "is_split_chunk",
        "majoraxis-drop spread-afterwashcm",
        "majoraxis-drop spread-beforewashcm",
        "metamerism f11/d65 mi",
        "nature of coating",
        "nature of dyes",
        "nature of fiber",
        "nir reflectance (%)",
        "original_stage_name",
        "peelrest.after50wash",
        "ph value",
        "ph value-other color",
        "ph value-white to pastel color",
        "pilling (7000 tours)",
        "pilling after (18000 revs.)",
        "pilling resis.martindale(5000 rubs)",
        "print_design_name",
        "print_name",
        "printed abrasion resistance using p600emery at 9kpa after 150 cycles",
        "printed abrasion resistance using unspecified abradant at 9kpa after 10000 cycles",
        "printed abrasion resistance using wool at 12kpa after 100000 cycles",
        "printed abrasion resistance using wool at 9kpa after 15000 cycles",
        "printed abrasion resistance using wool at 9kpa after 50000 cycles",
        "printed abrasion resistance using wool at 9kpa after 90000 cycles",
        "printed air permeability at 10 inch pressure in cm3/cm2/s",
        "printed air permeability at 10 inch pressure in ft3/ft2/s",
        "printed air permeability at 100 pas pressure in l/m2/s",
        "printed air permeability at 100 pas pressure in mm/s",
        "printed breaking strength of warp in dan",
        "printed breaking strength of warp in kgf",
        "printed breaking strength of warp in n",
        "printed breaking strength of weft in dan",
        "printed breaking strength of weft in kgf",
        "printed breaking strength of weft in n",
        "printed colourfastness to perspiration (acid) change in shade",
        "printed colourfastness to perspiration (acid) staining on acr",
        "printed colourfastness to perspiration (acid) staining on act",
        "printed colourfastness to perspiration (acid) staining on cot",
        "printed colourfastness to perspiration (acid) staining on nyl",
        "printed colourfastness to perspiration (acid) staining on pol",
        "printed colourfastness to perspiration (acid) staining on wol",
        "printed colourfastness to perspiration (alkaline) change in shade",
        "printed colourfastness to perspiration (alkaline) staining on acr",
        "printed colourfastness to perspiration (alkaline) staining on act",
        "printed colourfastness to perspiration (alkaline) staining on cot",
        "printed colourfastness to perspiration (alkaline) staining on nyl",
        "printed colourfastness to perspiration (alkaline) staining on pol",
        "printed colourfastness to perspiration (alkaline) staining on wol",
        "printed colourfastness to rubbing (dry)",
        "printed colourfastness to rubbing (dry)  wp",
        "printed colourfastness to rubbing (dry)  wt",
        "printed colourfastness to rubbing (wet)",
        "printed colourfastness to rubbing (wet)  wp",
        "printed colourfastness to rubbing (wet)  wt",
        "printed colourfastness to sea water change in shade",
        "printed colourfastness to sea water staining on acr",
        "printed colourfastness to sea water staining on act",
        "printed colourfastness to sea water staining on cot",
        "printed colourfastness to sea water staining on nyl",
        "printed colourfastness to sea water staining on pol",
        "printed colourfastness to sea water staining on wol",
        "printed colourfastness to washing change in shade",
        "printed colourfastness to washing staining on acr",
        "printed colourfastness to washing staining on act",
        "printed colourfastness to washing staining on cot",
        "printed colourfastness to washing staining on nyl",
        "printed colourfastness to washing staining on pol",
        "printed colourfastness to washing staining on wol",
        "printed colourfastness to water change in shade",
        "printed colourfastness to water staining on acr",
        "printed colourfastness to water staining on act",
        "printed colourfastness to water staining on cot",
        "printed colourfastness to water staining on nyl",
        "printed colourfastness to water staining on pol",
        "printed colourfastness to water staining on wol",
        "printed delta e (δe) under primary light (f11 10°)",
        "printed delta e (δe) under secondary light (d65 10°)",
        "printed delta e (δe) value",
        "printed dimensional stability of warp after one washes",
        "printed dimensional stability of warp in hot water",
        "printed dimensional stability of weft after one washes",
        "printed dimensional stability of weft in hot water",
        "printed ends per 10cms",
        "printed ends per cms",
        "printed ends per dm",
        "printed ends per inch",
        "printed fabric elongation in warp direction (fabric growth after 30mm-wp)",
        "printed fabric elongation in warp direction (wp)",
        "printed fabric elongation in weft direction (fabric growth after 30mm-wt)",
        "printed fabric elongation in weft direction (of fabric stretch-wt(15n))",
        "printed fabric elongation in weft direction (wt(15n))",
        "printed fabric elongation in weft direction (wt)",
        "printed picks per 10cms",
        "printed picks per cms",
        "printed picks per dm",
        "printed picks per inch",
        "printed tear strength of warp in dan",
        "printed tear strength of warp in kgf",
        "printed tear strength of warp in lbf",
        "printed tear strength of warp in n",
        "printed tear strength of warp using elmendorf method in dan",
        "printed tear strength of weft in dan",
        "printed tear strength of weft in kgf",
        "printed tear strength of weft in lbf",
        "printed tear strength of weft in n",
        "printed tear strength of weft using elmendorf method in dan",
        "printed thickness in mm",
        "printed water proofness tested at 20°c",
        "printed water proofness tested at 30°c for 30 minutes",
        "printed water proofness tested at 30°c for 60 minutes",
        "printed water proofness using dynamic method",
        "res. to acc.ageing",
        "res. to low temp.",
        "res. to low temp.(-40°c for 6 hrs.)",
        "resistance to flame-wp",
        "resistance to flame-wt",
        "seam slippage of yarn(mm)-wp",
        "seam slippage of yarn(mm)-wt",
        "sp pu film- wp",
        "sp pu film- wt",
        "sp pu film-wp",
        "sp pu film-wt",
        "spreading speed bottom-after 3 wash",
        "ss-wp kgf",
        "ss-wt kgf",
        "type of weave",
        "warp_fibre",
        "water repellency",
        "water repellency- after 5 wash",
        "water repellency- before wash",
        "water repellency-initial",
        "water resis.(6 kpa/min.)after 5wash",
        "water resistance-after 5 wash-250mm",
        "water resistance-after5wash-10000mm",
        "water resistance-before wash-250mm",
        "water resistance-beforewash-10000mm",
        "weft_fibre",
        "weight gsm",
        "width cm",
        "width cm (c to c)",
        "width cm (l to l)",
        "width cm (p to p)",
        "width cm (s to s)",
        "width mm",
        "gsm",
        "weight",
        "fabric bias distortion percentage",
        "fabric bow distortion percentage",
        "fabric bow distortion per inch",
        "fabric skew distortion percentage",
        "fabric skew distortion per inch",
        "fabric thickness",
        "test specifications" "testing specifications",
        "testing specifications after printing",
        "testing standards for printing",
        "test standards for printing",
        "test standards",
        "testing details",
        "testing details after printing",
        "testing after printing",
        "test specification",
        "test specification",
        "fabric thickness",
        "breaking strength",
        "bs",
        "tear strength",
        "perspiration",
        "fastness",
        "cf" "colourfastness",
        "color fastness",
        "colorfastness",
        "dimensional stability",
        "ds",
        "fabric elongation after printing",
        "fabric elongation",
        "water staining",
        "staining tets standards",
        "staining",
        "difference under primary light f11",
        "drop absorption",
        "drop spread",
        "water proofness",
        "water repellency",
        "water resistance",
        "wicking height",
        "coating adhesion",
        "peel strength",
        "peel resistance",
        "seal strength",
        "seam slippage",
        "pilling",
        "vapor resistance",
        "oil content percentage",
        "sp pu film",
        "fabric durability",
        "fabric strength",
        "rub resistance",
        "abrasion test",
        "abrasion",
        "water absorption",
    ],
    "testing after processing": [
        "% fabric distortion",
        "% fabric stability wp",
        "% fabric stability wt",
        "%bias",
        "%bow",
        "%bow-inch",
        "%ch dimen alkali(42%koh24hrs)wp",
        "%ch dimen alkali(42%koh24hrs)wt",
        "%skew",
        "%skew-inch",
        "abcap%(30%koh)-wp",
        "abcap%(30%koh)-wt",
        "abra emery cycle",
        "abso.of water drop-after washsec",
        "abso.of water drop-before sec",
        "absorption of water drop- sec",
        "add on %",
        "add on(gms)",
        "adhesion to backing (n/cm) 8310 x",
        "adhesion to backing (n/cm) 8310se",
        "adhesion to backing (n/cm) 832 mpx",
        "adhesion to backing (n/cm) 837 x",
        "adhesion to backing (n/cm) 839",
        "adhesion to backing (n/cm)-523",
        "adhesion to backing (n/cm)-525",
        "adhesion to backing(n/cm)523(24hrs)",
        "adhesion to backing(n/cm)523/24hrs.",
        "adhesion to backing(n/cm)525(24hrs)",
        "adhesion to backing(n/cm)525/24hrs.",
        "apcycl@1/2 inch (cfm)",
        "apcycl@1/2 inch (l/m2/s)",
        "appearance after 5x hl",
        "bend lngth-wp cms",
        "bend lngth-wp mn.cm2",
        "bend lngth-wt cms",
        "bias/bow%",
        "bleeding",
        "bleeding test--staining on cotton",
        "bleeding test-change in shade",
        "blocking test",
        "bow-mm",
        "breathtest-mg/cm2/h",
        "caact(30%koh)-wp",
        "caact(30%koh)-wt",
        "calendaring_details",
        "cf to light",
        "ch in dimensional",
        "ch in weight",
        "ch phy pro(100°c/2h)",
        "ch phy pro(71°c/30m)",
        "chunk_part",
        "co-eff.frict-wt",
        "co-eff.frict.wp",
        "crimp test % -wp",
        "crimp test % -wt",
        "deter.of shrink.after1wash @40°c-wp",
        "deter.of shrink.after1wash @40°c-wt",
        "deter.of shrink.after5wash @40°c-wp",
        "deter.of shrink.after5wash @40°c-wt",
        "extension at 20lbf (%) wp",
        "extension at 20lbf (%) wt",
        "fabric distortion mm",
        "finish",
        "finish content%",
        "flex res.-crack",
        "flex res.-flaking",
        "flex res.-wrinkle",
        "fr test (a. flame)",
        "fr test (a. glow)",
        "fr test (char length",
        "gloss value (gu)",
        "hydrostatic test cm",
        "is_split_chunk",
        "majoraxis-drop spread-afterwashcm",
        "majoraxis-drop spread-beforewashcm",
        "melting point",
        "metamerism f11/d65 mi",
        "nature of coating",
        "nature of dyes",
        "nature of fiber",
        "nir reflectance (%)",
        "oil content%",
        "oil repellency",
        "original_stage_name",
        "peel st.-wp gmf",
        "peel st.-wt gmf",
        "peelrest.after50wash",
        "per.of set %shrink.-wp",
        "per.of set %shrink.-wt",
        "per.of set ap@1/2 inch (ft3/ft2/m)",
        "per.of set thick inch",
        "petroleum ether extractable%",
        "ph value",
        "ph value-other color",
        "ph value-white to pastel color",
        "pilling (7000 tours)",
        "pilling after (18000 revs.)",
        "pilling resis.martindale(5000 rubs)",
        "pilling resistance",
        "processed abrasion resistance using p600emery at 9kpa after 150 cycles",
        "processed abrasion resistance using p600emery at 9kpa after 30 cycles",
        "processed abrasion resistance using p600emery at 9kpa after 50 cycles",
        "processed abrasion resistance using unspecified abradant at 9kpa after 10000 cycles",
        "processed abrasion resistance using unspecified abradant at unspecified pressure after 20000 cycles",
        "processed abrasion resistance using unspecified abradant at unspecified pressure after unspecified number of cycles",
        "processed abrasion resistance using wool at 12kpa after 100000 cycles",
        "processed abrasion resistance using wool at 9kpa after 15000 cycles",
        "processed abrasion resistance using wool at 9kpa after 30000 cycles",
        "processed abrasion resistance using wool at 9kpa after 50000 cycles",
        "processed abrasion resistance using wool at 9kpa after 60000 cycles",
        "processed abrasion resistance using wool at 9kpa after 90000 cycles",
        "processed air permeability at 1/2 inch pressure in ft3/ft2/m",
        "processed air permeability at 1/2 inch pressure in ft3/ft2/s",
        "processed air permeability at 1/2 inch pressure in l/m2/s",
        "processed air permeability at 10 inch pressure in cm3/cm2/s",
        "processed air permeability at 10 inch pressure in ft3/ft2/m",
        "processed air permeability at 10 inch pressure in ft3/ft2/s",
        "processed air permeability at 100 pas pressure in cm3/cm2/s",
        "processed air permeability at 100 pas pressure in l/m2/s",
        "processed air permeability at 100 pas pressure in mm/s",
        "processed air permeability at 200 pas pressure in mm/s",
        "processed air permeability at 2500 pas pressure in l/m2/s",
        "processed air permeability at 25mm pressure in cc/sec/cm2",
        "processed air permeability at 500 pas pressure in l/m2/s",
        "processed breaking strength of warp in dan",
        "processed breaking strength of warp in kgf",
        "processed breaking strength of warp in lbf",
        "processed breaking strength of warp in n",
        "processed breaking strength of weft in dan",
        "processed breaking strength of weft in kgf",
        "processed breaking strength of weft in lbf",
        "processed breaking strength of weft in n",
        "processed bursting strength in bar",
        "processed bursting strength in kgf/cm²",
        "processed bursting strength in psi",
        "processed colourfastness to perspiration (acid) change in shade",
        "processed colourfastness to perspiration (acid) staining on acr",
        "processed colourfastness to perspiration (acid) staining on act",
        "processed colourfastness to perspiration (acid) staining on cot",
        "processed colourfastness to perspiration (acid) staining on nyl",
        "processed colourfastness to perspiration (acid) staining on pol",
        "processed colourfastness to perspiration (acid) staining on wol",
        "processed colourfastness to perspiration (alkaline) change in shade",
        "processed colourfastness to perspiration (alkaline) staining on acr",
        "processed colourfastness to perspiration (alkaline) staining on act",
        "processed colourfastness to perspiration (alkaline) staining on cot",
        "processed colourfastness to perspiration (alkaline) staining on nyl",
        "processed colourfastness to perspiration (alkaline) staining on pol",
        "processed colourfastness to perspiration (alkaline) staining on wol",
        "processed colourfastness to perspiration change in shade",
        "processed colourfastness to perspiration staining on acr",
        "processed colourfastness to perspiration staining on act",
        "processed colourfastness to perspiration staining on cot",
        "processed colourfastness to perspiration staining on nyl",
        "processed colourfastness to perspiration staining on pol",
        "processed colourfastness to perspiration staining on wol",
        "processed colourfastness to rubbing (dry)",
        "processed colourfastness to rubbing (dry)  wp",
        "processed colourfastness to rubbing (dry)  wt",
        "processed colourfastness to rubbing (wet)",
        "processed colourfastness to rubbing (wet)  wp",
        "processed colourfastness to rubbing (wet)  wt",
        "processed colourfastness to sea water change in shade",
        "processed colourfastness to sea water staining on acr",
        "processed colourfastness to sea water staining on act",
        "processed colourfastness to sea water staining on cot",
        "processed colourfastness to sea water staining on nyl",
        "processed colourfastness to sea water staining on pol",
        "processed colourfastness to sea water staining on wol",
        "processed colourfastness to washing change in shade",
        "processed colourfastness to washing staining on acr",
        "processed colourfastness to washing staining on act",
        "processed colourfastness to washing staining on cot",
        "processed colourfastness to washing staining on nyl",
        "processed colourfastness to washing staining on pol",
        "processed colourfastness to washing staining on wol",
        "processed colourfastness to water change in shade",
        "processed colourfastness to water staining on acr",
        "processed colourfastness to water staining on act",
        "processed colourfastness to water staining on cot",
        "processed colourfastness to water staining on nyl",
        "processed colourfastness to water staining on pol",
        "processed colourfastness to water staining on wol",
        "processed delta e (δe) under primary light (f11 10°)",
        "processed delta e (δe) under secondary light (d65 10°)",
        "processed delta e (δe) value",
        "processed dimensional stability of warp after 2 washes",
        "processed dimensional stability of warp after 3 washes",
        "processed dimensional stability of warp after 5 washes",
        "processed dimensional stability of warp after one washes",
        "processed dimensional stability of warp in cold water",
        "processed dimensional stability of warp in hot water",
        "processed dimensional stability of warp to heat",
        "processed dimensional stability of warp to heat at 150°c/15minutes",
        "processed dimensional stability of weft after 2 washes",
        "processed dimensional stability of weft after 3 washes",
        "processed dimensional stability of weft after 5 washes",
        "processed dimensional stability of weft after one washes",
        "processed dimensional stability of weft in cold water",
        "processed dimensional stability of weft in hot water",
        "processed dimensional stability of weft to heat",
        "processed dimensional stability of weft to heat at 150°c/15minutes",
        "processed ends per 10cms",
        "processed ends per cms",
        "processed ends per dm",
        "processed ends per inch",
        "processed fabric elongation in warp direction (fabric growth after 30mm-wp)",
        "processed fabric elongation in warp direction (wp max.force)",
        "processed fabric elongation in warp direction (wp)",
        "processed fabric elongation in weft direction (fabric growth after 30mm-wt)",
        "processed fabric elongation in weft direction (of fabric stretch-wt(15n))",
        "processed fabric elongation in weft direction (wt max.force)",
        "processed fabric elongation in weft direction (wt(15n))",
        "processed fabric elongation in weft direction (wt(2.7 kgf))",
        "processed fabric elongation in weft direction (wt)",
        "processed picks per 10cms",
        "processed picks per cms",
        "processed picks per dm",
        "processed picks per inch",
        "processed tear strength of warp in dan",
        "processed tear strength of warp in gms",
        "processed tear strength of warp in kgf",
        "processed tear strength of warp in lbf",
        "processed tear strength of warp in mn",
        "processed tear strength of warp in n",
        "processed tear strength of warp using elmendorf method in dan",
        "processed tear strength of warp using elmendorf method in kgf",
        "processed tear strength of warp using elmendorf method in lbf",
        "processed tear strength of warp using elmendorf method in n",
        "processed tear strength of weft in dan",
        "processed tear strength of weft in gms",
        "processed tear strength of weft in kgf",
        "processed tear strength of weft in lbf",
        "processed tear strength of weft in n",
        "processed tear strength of weft using elmendorf method in dan",
        "processed tear strength of weft using elmendorf method in kgf",
        "processed tear strength of weft using elmendorf method in lbf",
        "processed tear strength of weft using elmendorf method in n",
        "processed thickness in inch",
        "processed thickness in micron",
        "processed thickness in mil",
        "processed thickness in mm",
        "processed water proofness tested at 100°c",
        "processed water proofness tested at 20°c",
        "processed water proofness tested at 30°c for 30 minutes",
        "processed water proofness tested at 30°c for 60 minutes",
        "processed water proofness tested at 80°c with minimum pressure of 80 cm",
        "processed water proofness using dynamic method",
        "processed water proofness with minimum pressure of 0.4 bar",
        "relaxation shrinkage- wp",
        "relaxation shrinkage- wt",
        "res. to low temp.",
        "res. to low temp.(-40°c for 6 hrs.)",
        "resistance to flame-wp",
        "resistance to flame-wt",
        "seam slippage (cm)-wp",
        "seam slippage (cm)-wt",
        "seam slippage (mm)-wp",
        "seam slippage (mm)-wt",
        "seam slippage of yarn(mm)-wp",
        "seam slippage of yarn(mm)-wt",
        "selvage req. bs-wp lbf",
        "selvage req. width inch",
        "shade_of_fabric",
        "silicone finish %",
        "size content%",
        "skew-mm",
        "skewing of-wp mm",
        "snagging resistance",
        "sp pu film- wp",
        "sp pu film- wt",
        "sp pu film-wp",
        "sp pu film-wt",
        "spreading speed bottom-after 3 wash",
        "ss-wp kgf",
        "ss-wt kgf",
        "thickmm-micro thick tester classic",
        "type of weave",
        "warp_fibre",
        "water proofness initial (pa)",
        "water repellency",
        "water repellency- after 10 wash",
        "water repellency- after 2 wash",
        "water repellency- after 20 wash",
        "water repellency- after 5 wash",
        "water repellency- back",
        "water repellency- before wash",
        "water repellency- front",
        "water repellency-after5wash+line",
        "water repellency-after5wash+tumble",
        "water repellency-initial",
        "water resis.(6 kpa/min.)after 5wash",
        "water resistance-after 5 wash-250mm",
        "water resistance-after5wash-10000mm",
        "water resistance-before wash-250mm",
        "water resistance-beforewash-10000mm",
        "water soluble %",
        "water vapor res.re (m2/pa/w)",
        "weft_fibre",
        "weight",
        "weight gsm",
        "weight gsm- coated",
        "weight oz/yd",
        "weight oz/yd2",
        "whiteness ind-cie",
        "wick.height 5xhl after 10min.-wp",
        "wick.height 5xhl after 10min.-wt",
        "wick.height 5xhl after 30min.-wp",
        "wick.height 5xhl after 30min.-wt",
        "wick.height-original after10min.-wp",
        "wick.height-original after10min.-wt",
        "wick.height-original after30min.-wp",
        "wick.height-original after30min.-wt",
        "width cm",
        "width cm (c to c)",
        "width cm (l to l)",
        "width cm (p to p)",
        "width cm (s to s)",
        "width inch",
        "width mm",
        "air permeability",
        "ap",
        "gsm",
        "weight",
        "fabric bias distortion percentage",
        "fabric bow distortion percentage",
        "fabric bow distortion per inch",
        "fabric skew distortion percentage",
        "fabric skew distortion per inch",
        "fabric thickness",
        "test specifications" "testing specifications",
        "testing specifications after processing",
        "testing standards for processing",
        "test standards for processing",
        "test standards",
        "testing details",
        "testing details after processing",
        "testing after processing",
        "test specification",
        "test specification",
        "fabric thickness",
        "breaking strength",
        "bs",
        "tear strength",
        "perspiration",
        "fastness",
        "cf" "colourfastness",
        "color fastness",
        "colorfastness",
        "dimensional stability",
        "ds",
        "fabric elongation after processing",
        "fabric elongation",
        "water staining",
        "staining tets standards",
        "staining",
        "difference under primary light f11",
        "drop absorption",
        "drop spread",
        "water proofness",
        "water repellency",
        "water resistance",
        "wicking height",
        "coating adhesion",
        "peel strength",
        "peel resistance",
        "seal strength",
        "seam slippage",
        "pilling",
        "vapor resistance",
        "oil content percentage",
        "sp pu film",
        "fabric durability",
        "fabric strength",
        "rub resistance",
        "abrasion test",
        "abrasion",
        "water absorption",
    ],
    "testing after weaving": [
        "% fabric stability wp",
        "% fabric stability wt",
        "bend lngth-wp cms",
        "bend lngth-wp cms (nozzle)",
        "bend lngth-wp mn.cm2",
        "bend lngth-wt cms",
        "chunk_part",
        "crimp test % -wp",
        "crimp test % -wt",
        "grey air permeability at 1/2 inch pressure in cm3/cm2/s",
        "grey air permeability at 1/2 inch pressure in ft3/ft2/m",
        "grey air permeability at 1/2 inch pressure in l/m2/s",
        "grey air permeability at 10 inch pressure in cm3/cm2/s",
        "grey air permeability at 10 inch pressure in ft3/ft2/m",
        "grey air permeability at 10 inch pressure in ft3/ft2/s",
        "grey air permeability at 100 pas pressure in cm3/cm2/s",
        "grey air permeability at 100 pas pressure in l/m2/s",
        "grey air permeability at 100 pas pressure in mm/s",
        "grey air permeability at 200 pas pressure in l/dm2/m",
        "grey air permeability at 200 pas pressure in l/m2/s",
        "grey air permeability at 200 pas pressure in mm/s",
        "grey air permeability at 2500 pas pressure in l/m2/s",
        "grey air permeability at 500 pas pressure in l/m2/s",
        "grey breaking strength of warp in dan",
        "grey breaking strength of warp in kgf",
        "grey breaking strength of warp in kn/mtr",
        "grey breaking strength of warp in lbf",
        "grey breaking strength of warp in n",
        "grey breaking strength of weft in dan",
        "grey breaking strength of weft in kgf",
        "grey breaking strength of weft in kn/mtr",
        "grey breaking strength of weft in lbf",
        "grey breaking strength of weft in n",
        "grey bursting strength in kgf/cm²",
        "grey delta e (δe) value",
        "grey dimensional stability of warp after one washes",
        "grey dimensional stability of weft after one washes",
        "grey ends per 10cms",
        "grey ends per cms",
        "grey ends per dm",
        "grey ends per inch",
        "grey ends per inch at filler",
        "grey ends per inch at nozzle",
        "grey fabric elongation (wp (nozzle))",
        "grey fabric elongation (wt (nozzle))",
        "grey fabric elongation in warp direction (wp)",
        "grey fabric elongation in weft direction (wt(15n))",
        "grey fabric elongation in weft direction (wt)",
        "grey picks per 10cms",
        "grey picks per cms",
        "grey picks per dm",
        "grey picks per inch",
        "grey picks per inch at nozzle",
        "grey tear strength of warp in dan",
        "grey tear strength of warp in kgf",
        "grey tear strength of warp in lbf",
        "grey tear strength of warp in mn",
        "grey tear strength of warp in n",
        "grey tear strength of warp using elmendorf method in dan",
        "grey tear strength of warp using elmendorf method in kgf",
        "grey tear strength of warp using elmendorf method in n",
        "grey tear strength of weft in dan",
        "grey tear strength of weft in kgf",
        "grey tear strength of weft in lbf",
        "grey tear strength of weft in n",
        "grey tear strength of weft using elmendorf method in dan",
        "grey tear strength of weft using elmendorf method in kgf",
        "grey tear strength of weft using elmendorf method in n",
        "grey thickness in inch",
        "grey thickness in micron",
        "grey thickness in mil",
        "grey thickness in mm",
        "grey thickness in mm at filler",
        "grey thickness in mm at nozzle",
        "index puncture n",
        "is_split_chunk",
        "nature of fiber",
        "original_stage_name",
        "size content%",
        "sizing_details",
        "thickmm-micro thick tester classic",
        "type of weave",
        "type of weave (nozzle)",
        "w permea(l/cm2/s)",
        "warp_fibre",
        "weave",
        "weft_fibre",
        "weight",
        "weight gsm",
        "weight gsm (nozzle)",
        "weight oz/yd2",
        "width cm",
        "width cm (nozzle)",
        "width cm (s to s)",
        "width inch",
        "width mm",
        "width",
        "gsm",
        "weight",
        "air permeability",
        "ap",
        "fabric thickness",
        "test specifications",
        "testing specifications",
        "testing specifications after weaving",
        "testing standards for weaving",
        "test standards for weaving",
        "test standards",
        "testing details",
        "testing details after weaving",
        "testing after weaving",
        "test specification",
        "test specification",
        "fabric thickness",
        "breaking strength",
        "bs",
        "tear strength",
    ],
    "vdr": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "finishing details after processing",
        "full article",
        "machine used in processing",
        "vdr",
        "vdr drying",
        "vdr-1",
    ],
    "warp and weft yarn details": [
        "article number",
        "article_no",
        "bomid_warp",
        "bomid_weft",
        "drawing and texturing in warp yarn",
        "drawing and texturing in weft yarn",
        "dullness/brightness of warp",
        "fibre in warp",
        "fibre in weft",
        "filament in warp yarn",
        "filament in weft yarn",
        "full_article",
        "itemid_warp",
        "itemid_weft",
        "number of beams",
        "number of twist in warp yarn",
        "number of twist in weft yarn",
        "ply in warp yarn",
        "ply in weft yarn",
        "quality number",
        "reed space",
        "shade code of warp",
        "shade code of weft",
        "shade of warp yarn",
        "total ends",
        "twist direction in warp yarn",
        "twist direction in weft yarn",
        "type of warping",
        "warp count",
        "warp denier",
        "warp yarn elongation",
        "warp yarn shrinkage",
        "warp yarn tenacity",
        "warp yarn type",
        "warp yarn vendor",
        "weave of fabric",
        "weft count",
        "weft denier",
        "weft yarn brightness",
        "weft yarn elongation",
        "weft yarn shrinkage",
        "weft yarn sizing details",
        "weft yarn tenacity",
        "weft yarn type",
        "weft yarn vendor",
        "width of griege fabric",
    ],
    "washing": [
        "article no",
        "article number",
        "article_no",
        "calendaring details",
        "finishing details after processing",
        "full article",
        "jet",
        "machine used in processing",
        "no of ends",
        "no. of ends",
        "speed",
        "temp",
        "tension",
        "water",
    ],
    "weaving": [
        "article no",
        "article number",
        "article_no",
        "back rest position",
        "beam winding tension",
        "beaming speed",
        "config_id",
        "creel tension (post position)",
        "density",
        "drawing seq body",
        "drawing seq sleavege",
        "full article",
        "full_article",
        "grey width(cms)",
        "height & amound of heald frames",
        "lease position",
        "loom speed rpm",
        "no of heald frames",
        "number_of_ends_in_warp",
        "pick",
        "press roll pressure",
        "pump stroke ( mm )",
        "reed",
        "reed space (inches)",
        "s.wrap tension contribution",
        "shed crossing timing",
        "sizing details",
        "speed",
        "total ends",
        "total ends of warp",
        "traverse",
        "warp beam tension",
        "warping m/c speed",
        "water ltr/kg",
        "water ltr/min",
        "weave",
        "weave_of_fabric",
        "weft arrival timing",
        "weft cutting timing",
    ],
}

# ---------- LOAD CHUNKS ---------- #
print(f"📦 Loading chunks from: {CHUNK_FILE}")
with open(CHUNK_FILE, "r", encoding="utf-8") as f:
    chunks = json.load(f)

if not isinstance(chunks, list):
    raise ValueError("❌ Loaded data is not a list of chunks.")
print(f"✅ Loaded {len(chunks)} chunks")

# ---------- LOAD EMBEDDING MODEL ---------- #
print(f"🔍 Loading model: {MODEL_NAME}")
model = SentenceTransformer(MODEL_NAME)

# ---------- INIT WEAVIATE CLIENT ---------- #
client = WeaviateClient(WEAVIATE_URL)

# ---------- SCHEMA SETUP ---------- #
if client.schema.exists(CLASS_NAME):
    print(f"❌ Deleting old class {CLASS_NAME}...")
    client.schema.delete_class(CLASS_NAME)

print(f"📁 Creating class {CLASS_NAME} in Weaviate...")
client.schema.create_class(
    {
        "class": CLASS_NAME,
        "vectorizer": "none",
        "properties": [
            {"name": "content", "dataType": ["text"]},
            {"name": "metadata", "dataType": ["text"]},
            {"name": "article", "dataType": ["text"]},
            {"name": "stage", "dataType": ["text"]},
            {"name": "parameter_names", "dataType": ["text[]"]},
        ],
    }
)


# ---------- HELPER: Detect stage and parameter names ---------- #
def detect_stage(content, metadata):
    stage = metadata.get("stage") or metadata.get("Stage")
    if stage:
        return stage.lower()
    for process in PROCESS_NAMES:
        if process in content.lower():
            return process
    return None


def extract_parameters(content, stage):
    matched_params = []
    possible_params = PROCESS_PARAMETERS.get(stage, [])
    for param in possible_params:
        if re.search(rf"\b{re.escape(param)}\b", content.lower()):
            matched_params.append(param)
    return matched_params


# ---------- EMBEDDING + UPLOAD ---------- #
print("📤 Uploading chunks with vector embeddings and metadata...")

missing_articles = 0
uploaded = 0

with client.batch(batch_size=BATCH_SIZE) as batch:
    for chunk in tqdm(chunks, desc="✅ Uploading"):
        content = chunk.get("content", "")
        metadata = chunk.get("metadata", {})

        stage = detect_stage(content, metadata)
        parameter_names = extract_parameters(content, stage) if stage else []
        parameter_names = [p.lower() for p in parameter_names]

        # Robust article extraction (fallback to flat_metadata)
        article = (
            metadata.get("article")
            or metadata.get("flat_metadata", {}).get("article")
            or ""
        )
        article = str(article).strip()

        if not article:
            missing_articles += 1
            print(f"⚠️ Missing article in chunk: {content[:100]}...")
            continue  # Skip if article is completely missing

        vector = model.encode(content, normalize_embeddings=True)

        batch.add_data_object(
            data_object={
                "content": content,
                "metadata": json.dumps(metadata),
                "article": article,
                "stage": (stage or "").lower(),
                "parameter_names": parameter_names,
            },
            class_name=CLASS_NAME,
            vector=vector,
        )
        uploaded += 1

print(
    f"\n✅ Upload complete. Uploaded: {uploaded} chunks | Skipped: {missing_articles} due to missing article.\n"
)

# ---------- QUICK TEST ---------- #
print("🔎 Running test query for article = '8222' ...")
test_article = "8222"
results = (
    client.query.get(CLASS_NAME, ["article", "stage", "metadata"])
    .with_where({"path": ["article"], "operator": "Equal", "valueText": test_article})
    .with_limit(3)
    .do()
)

print(json.dumps(results, indent=2))
